# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cancellation.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mysql1
from PyQt5.QtWidgets import QMessageBox
class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0,0,951,891))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images3.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 40, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(21, 255, 240);\n"
"\n"
"font: 87 16pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(350, 50, 321, 31))
        self.textEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(21, 255, 240);\n"
"\n"
"font: 87 16pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 200, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(21, 255, 240);\n"
"\n"
"font: 87 16pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 280, 241, 16))
        self.label_5.setStyleSheet("color:rgb(21, 255, 240);\n"
"\n"
"font: 87 16pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_5.setObjectName("label_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(350, 270, 321, 31))
        self.textEdit_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 340, 311, 51))
        self.label_6.setStyleSheet("color:rgb(21, 255, 240);\n"
"\n"
"font: 87 12pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_6.setObjectName("label_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(350, 350, 321, 31))
        self.textEdit_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 440, 401, 31))
        self.label_7.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color: rgb(255, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 490, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 490, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.dateEdit_ = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_.setGeometry(QtCore.QRect(350, 110, 321, 31))
        self.dateEdit_.setWrapping(False)
        self.dateEdit_.setCalendarPopup(True)
        self.dateEdit_.setObjectName("dateEdit_")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(350, 190, 321, 31))
        self.dateEdit_2.setWrapping(False)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TRAIN NAME"))
        self.label_3.setText(_translate("MainWindow", "DATE OF TRAVEL"))
        self.label_4.setText(_translate("MainWindow", "DATE OF BIRTH"))
        self.label_5.setText(_translate("MainWindow", "PASSENGER NAME"))
        self.label_6.setText(_translate("MainWindow", "PHONE NUMBER GIVEN IN TICKET"))
        self.label_7.setText(_translate("MainWindow", "DO YOU WANT TO CANCEL YOUR TICKET"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton_2.setText(_translate("MainWindow", "CANCEL"))
        self.pushButton.clicked.connect(self.cancellation_ticket)
        self.pushButton_2.clicked.connect(self.cancel) 
    def cancellation_ticket(self):
              train_name=self.textEdit.toPlainText()
              passenger_name=self.textEdit_2.toPlainText()
              phone_number=self.textEdit_3.toPlainText()
              date_of_travel1=self.dateEdit_.date()
              date_of_travel=date_of_travel1.toPyDate()   
              date_of_birth1=self.dateEdit_2.date()
              date_of_birth=date_of_birth1.toPyDate() 
              mycon=mysql1.connect(host="localhost",user="root",passwd="phonetest@123",database="first_page")
              cursor=mycon.cursor()
              ST="SELECT count(PASSENGER_NAME) FROM railway_database where TRAIN_NAME='{0}' AND PHONE_NUMBER='{1}' AND PASSENGER_DATE_OF_BIRTH='{2}' AND DATE_OF_TRAVEL='{3}' ".format(train_name,phone_number,date_of_birth,date_of_travel)
              cursor.execute(ST) 
              mycon.close()
              data1=cursor.fetchone()
              data=int(data1[0])
              print(data)
              if(data>=1):
                     mycon2=mysql1.connect(host="localhost",user="root",passwd="phonetest@123",database="first_page")
                     cursor=mycon2.cursor()
                     ST="delete from railway_database where TRAIN_NAME='{0}' AND PHONE_NUMBER='{1}' AND PASSENGER_DATE_OF_BIRTH='{2}' AND DATE_OF_TRAVEL='{3}' AND PASSENGER_NAME='{4}' ".format(train_name,phone_number,date_of_birth,date_of_travel,passenger_name)
                     cursor.execute(ST) 
                     mycon2.commit()
                     mycon2.close()
                     msg=QMessageBox()
                     msg.setText("TICKET CANCELLED!!!!")
                     X=msg.exec_()
              else:
                msg2=QMessageBox()
                msg2.setText("WRONG INFORMATION ENTERED TRY AGAIN!!!")
                X=msg2.exec_()
    def cancel(self):
            msg=QMessageBox()
            msg.setText("cancelled")
            X=msg.exec_()   
            sys.exit(app.exec_())            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
